# Run this command to start the database:
# docker-compose up --build
version: "3"
services:
  db:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg15
    ports:
      - 5634:5432
    restart: always
    environment:
      - POSTGRES_DB=kingface
      - POSTGRES_USER=kingface
      - POSTGRES_PASSWORD=kingface
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
