module.exports = {
  semi: true,
  tabWidth: 2,
  printWidth: 80,
  singleQuote: false,
  trailingComma: "all",
  jsxSingleQuote: false,
  bracketSpacing: true,
  arrowParens: "always",
  endOfLine: "lf",
  useTabs: false,
  importOrder: [
    "^@app/(.*)$",
    "^@components/(.*)$",
    "^@data/(.*)$",
    "^@hooks/(.*)$",
    "^@lib/(.*)$",
    "^@styles/(.*)$",
    "^@types/(.*)$",
    "^@utils/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: ["@trivago/prettier-plugin-sort-imports"],
};
